name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck shfmt bats redis-server ffmpeg curl lowdown
          curl -L https://github.com/joewalnes/websocketd/releases/download/v0.4.1/websocketd-0.4.1_amd64.deb -o websocketd.deb
          sudo dpkg -i websocketd.deb
      - name: Install Node dependencies
        run: |
          npm ci --prefix modules/realtime/node
          npm ci --prefix modules/ws-fallback/node
      - name: Run shellcheck
        run: shellcheck -x -e SC1091 $(git ls-files '*.sh')
      - name: Run shfmt
        run: shfmt -i 2 -sr -d $(git ls-files '*.sh' '*.bats')
      - name: Run tests
        run: bats $(git ls-files '*.bats')
